"""empty message

Revision ID: 5fe718dba30c
Revises: 99194d2713cf
Create Date: 2019-05-07 22:04:38.589391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe718dba30c'
down_revision = '99194d2713cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.add_column('track', sa.Column('is_archived', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'is_archived')
    op.drop_column('track', 'image_url')
    # ### end Alembic commands ###
